server:
  port: 8080
spring:
  application:
    name: rose-zuul
  # 配置中心
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: roseconfig
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:876/eureka/
